const Joi = require("joi");

const createFormSchema = Joi.object({
  country: Joi.string().required(),
  person: Joi.string().required(),
  documentType: Joi.string().required(),
  documentNumber: Joi.string().required(),
  nationality: Joi.string().required(),
  phoneCode: Joi.string().required(),
  adopterType: Joi.string().required(),
  isAddressPublic: Joi.string().required(),
  addressPublic: Joi.optional(),
  // dni: Joi.string().required(),
  firstName: Joi.string().required(),
  firstLastName: Joi.string().required(),
  secondName: Joi.optional(),
  secondLastName: Joi.string().required(),
  birthDate: Joi.string().required(),
  gender: Joi.string().required(),
  cellphone: Joi.string().required(),
  email: Joi.string().required(),
  department: Joi.string().required(),
  province: Joi.string().required(),
  district: Joi.string().required(),
  address: Joi.string().required(),
  registerEntity: Joi.string().required(),
  jurament1: Joi.boolean().required(),
  isMicrochip: Joi.string().required(),
  jurament3: Joi.boolean().required(),
  microchip: Joi.optional(),
  dateMicrochip: Joi.optional(),
  firstNamePet: Joi.string().required(),
  countryPet: Joi.string().required(),
  birthDatePet: Joi.string().required(),
  adoptionDate: Joi.string().required(),
  genderPet: Joi.string().required(),
  specie: Joi.string().required(),
  race: Joi.string().required(),
  color: Joi.string().required(),
  isSterilized: Joi.string().required(),
  fatherMicrochip: Joi.optional(),
  motherMicrochip: Joi.optional(),
  // isPayment: Joi.optional(),
  files: Joi.optional(),
});

const updateFormSchema = Joi.object({
  country: Joi.string().required(),
  person: Joi.string().required(),
  documentType: Joi.string().required(),
  documentNumber: Joi.string().required(),
  nationality: Joi.string().required(),
  phoneCode: Joi.string().required(),
  adopterType: Joi.string().required(),
  isAddressPublic: Joi.string().required(),
  addressPublic: Joi.optional(),
  // dni: Joi.string().required(),
  firstName: Joi.string().required(),
  firstLastName: Joi.string().required(),
  secondName: Joi.optional(),
  secondLastName: Joi.string().required(),
  birthDate: Joi.string().required(),
  gender: Joi.string().required(),
  cellphone: Joi.string().required(),
  email: Joi.string().required(),
  department: Joi.string().required(),
  province: Joi.string().required(),
  district: Joi.string().required(),
  address: Joi.string().required(),
  registerEntity: Joi.string().required(),
  jurament1: Joi.boolean().required(),
  isMicrochip: Joi.string().required(),
  jurament3: Joi.boolean().required(),
  microchip: Joi.optional(),
  dateMicrochip: Joi.optional(),
  firstNamePet: Joi.string().required(),
  countryPet: Joi.string().required(),
  birthDatePet: Joi.string().required(),
  adoptionDate: Joi.string().required(),
  genderPet: Joi.string().required(),
  specie: Joi.string().required(),
  race: Joi.string().required(),
  color: Joi.string().required(),
  isSterilized: Joi.string().required(),
  fatherMicrochip: Joi.optional(),
  motherMicrochip: Joi.optional(),
  isPayment: Joi.boolean().required(),
  status: Joi.optional(),
  files: Joi.optional(),
});

module.exports = {
  createFormSchema,
  updateFormSchema,
};
